## Función de activación y Maxpooling

<h3>Objetivo de este cuaderno<h3>
<h5> 1. Aprender a aplicar una función de activación.</h5>
<h5> 2. Aprender sobre el max pooling. </h5>

In [1]:
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import numpy as np
from scipy import ndimage, misc

C:\Users\Josue Santana Robled\AppData\Local\Temp\ipykernel_14440\3053585304.py:5: DeprecationWarning: scipy.misc is deprecated and will be removed in 2.0.0
  from scipy import ndimage, misc


### Funciones de Activación

Al igual que en una red neuronal, se aplica una función de activación al mapa de activación, tal y como se muestra en la siguiente imagen:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter%206/6.1.3block_digram.png" width="1000," align="center">


Cree un núcleo y una imagen como de costumbre. Establezca el sesgo en cero:

In [2]:
conv = nn.Conv2d(in_channels=1, out_channels=1,kernel_size=3)
Gx=torch.tensor([[1.0,0,-1.0],[2.0,0,-2.0],[1.0,0,-1.0]])
conv.state_dict()['weight'][0][0]=Gx
conv.state_dict()['bias'][0]=0.0
conv.state_dict()

OrderedDict([('weight',
              tensor([[[[ 1.,  0., -1.],
                        [ 2.,  0., -2.],
                        [ 1.,  0., -1.]]]])),
             ('bias', tensor([0.]))])

In [3]:
image=torch.zeros(1,1,5,5)
image[0,0,:,2]=1
image

tensor([[[[0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0.]]]])

La siguiente imagen muestra la imagen y el núcleo:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter%206/6.1.3kernal_out.png" width="500," align="center">


Aplicar convolución a la imagen:

In [4]:
Z=conv(image)
Z

tensor([[[[-4.,  0.,  4.],
          [-4.,  0.,  4.],
          [-4.,  0.,  4.]]]], grad_fn=<ConvolutionBackward0>)

Aplica la función de activación al mapa de activación. Esto aplicará la función de activación a cada elemento del mapa de activación.


In [5]:
A=torch.relu(Z)
A

tensor([[[[0., 0., 4.],
          [0., 0., 4.],
          [0., 0., 4.]]]], grad_fn=<ReluBackward0>)

In [6]:
relu = nn.ReLU()
relu(Z)

tensor([[[[0., 0., 4.],
          [0., 0., 4.],
          [0., 0., 4.]]]], grad_fn=<ReluBackward0>)

El proceso se resume en la siguiente figura. La función Relu se aplica a cada elemento. Todos los elementos menores que cero se asignan a cero. Los componentes restantes no cambian.

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter%206/6.2.3_block_example.gif" width="1000," align="center">

#### Agrupación máxima

Considera la siguiente imagen:

In [7]:
image1=torch.zeros(1,1,4,4)
image1[0,0,0,:]=torch.tensor([1.0,2.0,3.0,-4.0])
image1[0,0,1,:]=torch.tensor([0.0,2.0,-3.0,0.0])
image1[0,0,2,:]=torch.tensor([0.0,2.0,3.0,1.0])

image1

tensor([[[[ 1.,  2.,  3., -4.],
          [ 0.,  2., -3.,  0.],
          [ 0.,  2.,  3.,  1.],
          [ 0.,  0.,  0.,  0.]]]])

El max pooling simplemente toma el valor máximo de cada región. Consideremos la siguiente imagen. Para la primera región, el max pooling simplemente toma el elemento más grande de la región amarilla.


<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter%206/6.1.3maxpool_1.png" width="500," align="center">

La región cambia y el proceso se repite. El proceso es similar a la convolución y se muestra en la siguiente figura:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter%206/6.1.3_max_pool_animation.gif" width="500," align="center">

Cree un objeto maxpooling en 2D de la siguiente manera y realice el max pooling de la siguiente manera:

In [8]:
max1=torch.nn.MaxPool2d(2,stride=1)
max1(image1)

tensor([[[[2., 3., 3.],
          [2., 3., 3.],
          [2., 3., 3.]]]])

Si el paso se establece en Ninguno (su configuración predeterminada), el proceso simplemente tomará el máximo en un área prescrita y se desplazará en consecuencia, como se muestra en la siguiente figura:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter%206/6.1.3_max_pool_animation_2.gif" width="500," align="center">

Aquí esta el codigo en Pythorch:

In [9]:
max1=torch.nn.MaxPool2d(2)
max1(image1)

tensor([[[[2., 3.],
          [2., 3.]]]])